Wed Dec 23 22:31:49 CET 2020 : Access denied for user 'testdb_user'@'%' to database 'mario1'
Wed Dec 23 22:31:49 CET 2020 : java.sql.SQLSyntaxErrorException: Access denied for user 'testdb_user'@'%' to database 'mario1'
Wed Dec 23 22:31:50 CET 2020 : Access denied for user 'testdb_user'@'%' to database 'mario1'
Wed Dec 23 22:31:50 CET 2020 : java.sql.SQLSyntaxErrorException: Access denied for user 'testdb_user'@'%' to database 'mario1'
Wed Dec 23 22:33:39 CET 2020 : Public Key Retrieval is not allowed
Wed Dec 23 22:33:39 CET 2020 : java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
Wed Dec 23 22:33:41 CET 2020 : Public Key Retrieval is not allowed
Wed Dec 23 22:33:41 CET 2020 : java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
Wed Dec 23 22:35:05 CET 2020 : Access denied for user 'testdb_user'@'localhost' (using password: YES)
Wed Dec 23 22:35:05 CET 2020 : java.sql.SQLException: Access denied for user 'testdb_user'@'localhost' (using password: YES)
Wed Dec 23 22:36:01 CET 2020 : The connection property 'useSSL' acceptable values are: 'TRUE', 'FALSE', 'YES' or 'NO'. The value 'false1' is not acceptable.
Wed Dec 23 22:36:01 CET 2020 : java.sql.SQLException: The connection property 'useSSL' acceptable values are: 'TRUE', 'FALSE', 'YES' or 'NO'. The value 'false1' is not acceptable.
Wed Dec 23 22:36:07 CET 2020 : The connection property 'useSSL' acceptable values are: 'TRUE', 'FALSE', 'YES' or 'NO'. The value 'false1' is not acceptable.
Wed Dec 23 22:36:07 CET 2020 : java.sql.SQLException: The connection property 'useSSL' acceptable values are: 'TRUE', 'FALSE', 'YES' or 'NO'. The value 'false1' is not acceptable.
Wed Dec 23 23:09:53 CET 2020 : Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:09:53 CET 2020 : java.sql.SQLException: Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:22:55 CET 2020 : Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:22:55 CET 2020 : java.sql.SQLException: Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:25:57 CET 2020 : Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:25:57 CET 2020 : java.sql.SQLException: Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:26:47 CET 2020 : Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:26:47 CET 2020 : java.sql.SQLException: Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:36:55 CET 2020 : Access denied for user 'testdb_users'@'localhost' (using password: YES)
Wed Dec 23 23:36:55 CET 2020 : java.sql.SQLException: Access denied for user 'testdb_users'@'localhost' (using password: YES)
Tue Jan 05 15:34:29 CET 2021 : Column 'pizza_i' not found.
Tue Jan 05 15:34:29 CET 2021 : java.sql.SQLException: Column 'pizza_i' not found.
Tue Jan 05 21:40:39 CET 2021 : Column 'pizza_i' not found.
Tue Jan 05 21:42:50 CET 2021 : Column 'pizza_i' not found.
java.sql.SQLException: Column 'pizza_i' not found.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:548)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:807)
	at persistence.DbMenuCardMapper.getAllPizzas(DbMenuCardMapper.java:28)
	at ui.MainMenu.showMenuCard(MainMenu.java:335)
	at ui.MainMenu.mainMenuLoop(MainMenu.java:34)
	at Main.main(Main.java:9)
